[program:flight_control_system]
command=python3 /app/flight_control_main.py
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/mugin3/fcs_stdout.log
stderr_logfile=/var/log/mugin3/fcs_stderr.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
environment=PYTHONUNBUFFERED=1
